# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df855851bc86ba4513e5fd6c7172be90554f20d837722e1d7aefd91e6e6730b53c820181e7f7fda77e46bf33423816544349f3bd136e8d60024294946d2527d4

test:
  secret_key_base: eabfa61e9dd04e08152a4ee759d969a0f5b55afe1dc98b31a80b0cdc0c4baf4819fd5ded336fbef0d1be9f45b1b0b29d81df7b5a2cda5d65715d3901077c7671

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
